Three new token metadata+assets [CERRA, SKY, STRIKE]
MELD-labs/meld-supported-config pull request #63
Opened 2024-09-12 18:25 UTC by rebelC0der

# Hello MELD Team! &#128736;
I am submitting this pull request to add details for three Cardano tokens: Cerra (CERRA), Sky (SKY), and Strike (STRIKE) in the repository. I have followed the prescribed guidelines and ensured that all necessary details are accurate and align with the required data structure. Below is an overview of the tokens and the associated changes.
- [x] I have checked that the format of my PR follows the contribution guidelines

### Token Overview &#128221;
- Token Names: Cerra, Sky, Strike
- Token Tickers: CERRA, SKY, STRIKE
- Blockchain: Cardano (for all tokens)
- Token Type: Native Cardano tokens (for all tokens)
- Primary Use Cases: 
  - Cerra: Utility token for the Cerra decentralized profit-sharing finance hub, enabling staking, governance, and profit-sharing on Cardano.
  - Sky: Utility token for Sky Protocol, a universal Layer 2 solution to enhance blockchain scalability across multiple networks.
  - Strike: Governance and utility token for Strike Finance, an open-source derivatives protocol on Cardano designed for trading and hedging.

### Organization Details &#127970;
- Organization Names: Cerra, Sky Protocol, Strike Finance
- Websites: 
  - Cerra: https://cerra.io
  - Sky Protocol: https://www.skyprotocol.org
  - Strike Finance: https://www.strikefinance.org
- Mission & Vision:
  - Cerra: To build a decentralized finance (DeFi) hub that allows users to participate in profit-sharing, governance, and staking while benefiting from a secure and transparent ecosystem.
  - Sky: To provide a universal Layer 2 solution that addresses blockchain scalability and interoperability issues, making it easier for dApps to achieve faster transactions and reduced fees.
  - Strike: To offer an open-source, user-friendly derivatives protocol on Cardano that enables traders to engage in various derivatives markets with robust security and liquidity.

### Changes Proposed &#128260;
#### For Additions:
- Community Demand: 
  - Rising interest in decentralized profit-sharing and governance models on Cardano (Cerra)
  - Increasing need for scalable blockchain solutions to support dApp growth and performance (Sky Protocol)
  - Growing demand for accessible and user-friendly derivatives trading platforms in the Cardano ecosystem (Strike Finance)
- Unique Value Proposition:
  - Cerra: Decentralized finance hub with a focus on profit-sharing, governance, and staking.
  - Sky: A universal Layer 2 scalability solution compatible with multiple blockchains, enhancing dApp performance.
  - Strike: A comprehensive derivatives protocol with an intuitive interface and advanced trading tools, tailored for Cardano.
- Technical Robustness: 
  - All tokens are built on Cardano's secure and scalable infrastructure.
  - Cerra utilizes smart contracts for profit-sharing and governance features.
  - Sky Protocol focuses on Layer 2 solutions to offer faster and more cost-effective transactions.
  - Strike Finance leverages Cardano’s eUTxO model to ensure efficient and secure derivatives trading.
- Compliance and Security: 
  - All tokens adhere to Cardano's security standards and best practices.
  - Regular security audits and updates are performed to ensure platform integrity and safety.

### Rationale for Inclusion/Modification &#128200;
- Benefits to the Repository: 
  - Adds diverse Cardano tokens representing decentralized profit-sharing (Cerra), Layer 2 scalability solutions (Sky), and derivatives trading (Strike).
  - Expands the range of DeFi use cases and technical innovations represented in the MELD ecosystem.
- Impact on Community:
  - Provides exposure to new projects that enhance DeFi, blockchain scalability, and derivatives trading capabilities on Cardano.
  - Attracts users interested in profit-sharing, scalable solutions for dApps, and robust derivatives markets within the Cardano ecosystem.

2024-09-12 18:37 UTC, rebelC0der commented
How can we re-trigger the Actions? I don't see that option.

2024-09-13 05:15 UTC, thuyvu17 approved these changes

2024-09-13 05:17 UTC, thuyvu17 requested changes
please rebase your branch.

2024-09-13 09:10 UTC, thuyvu17 requested changes
still cannot be rebased due to conflicts

2024-09-13 09:39 UTC, closed without merging