Add eigenlayer token
MELD-labs/meld-supported-config pull request #84
Opened 2024-10-02 15:26 UTC by unknownking07

# Hello MELD Team! &#128736;
I am submitting this pull request to [add] details for the [EigenLayer] ([EIGEN]) in the repository. I have followed the prescribed guidelines and ensured that all necessary details are accurate and align with the required data structure. Below is an overview of the token and the associated changes.

- [] I have checked that the format of my PR follows the contribution guidelines

### Token Overview &#128221;
- Token Name: [EigenLayer]
- Token Ticker: [EIGEN]
- Blockchain: [Ethereum]
- Token Type: [ERC20]
- Primary Use Case: [The EIGEN token is a universal intersubjective work token designed for EigenLayer, enabling security for various digital tasks that are not just objectively verifiable but also intersubjectively attributable. Unlike traditional work tokens that are tied to one specific digital task or objective faults (verifiable on-chain), EIGEN addresses a broader category of faults where multiple external observers agree on whether the task was performed correctly. This expands the range of tasks that can be securely managed on a blockchain. EIGEN tokens are used for:

Staking for intersubjective faults on the EigenLayer platform.
Performing validation tasks across various Actively Validated Services (AVS).
Incentivizing and penalizing operators based on their performance.]

### Organization Details &#127970;
- Organization Name: [Eigen Foundation]
- Website: [https://www.eigenlayer.xyz/]
- Mission & Vision: [EigenLayer’s mission is to enhance Ethereum’s security by enabling stakers to “restake” their assets across multiple decentralized services, fostering a more efficient and scalable staking economy. Its vision is to make Ethereum’s security a shared resource that supports the growth of decentralized networks, lowering barriers for new protocols and promoting greater interoperability within the ecosystem.]

### Changes Proposed &#128260;

#### For Additions:
- Community Demand: [Evidence of Community Interest]
- Unique Value Proposition: [What Sets This Token Apart]
- Technical Robustness: [Evidence of Technical Soundness]
- Compliance and Security: [Information on Compliance with Security Standards]

#### For Modifications:
- Field Modified: [Field Name]
- Old Value: [Old Value]
- New Value: [New Value]
- Reason for Modification: [Explanation of the Change]

### Rationale for Inclusion/Modification &#128200;
- Benefits to the Repository: [Benefits of Adding/Modifying This Token]
- Impact on Community: [How the Community Will Benefit]

2024-10-03 10:42 UTC, pepebndc requested changes

2024-10-03 10:42 UTC, pepebndc commented on networks/ethereum/tokens/0xec53bF9167f50cDEB3Ae105f56099aaaB9061F83.json
> +  "tokenAddress": "0x0d8775f648430679a709e98d2b0cb6250d2887ef",
this token address belongs to a different token.

Put the correct token address here as well

2024-10-03 10:42 UTC, pepebndc commented on networks/ethereum/tokens/0xec53bF9167f50cDEB3Ae105f56099aaaB9061F83.json
> +  "tokenAddress": "0x0d8775f648430679a709e98d2b0cb6250d2887ef",
```suggestion
  "tokenAddress": "0xec53bF9167f50cDEB3Ae105f56099aaaB9061F83",
```

2024-10-04 07:32 UTC, thuyvu17 approved these changes

2024-10-04 07:50 UTC, pepebndc approved these changes

2024-10-04 07:50 UTC, merged