[ERC20] Token metadata+assets [CGPT, STG, CULT]
MELD-labs/meld-supported-config pull request #86
Opened 2024-10-03 11:34 UTC by rebelC0der

# Hello MELD Team! &#128736;
I am submitting this pull request to add details for three Ethereum tokens: Cult DAO (CULT), ChainGPT (CGPT), and Stargate Finance (STG) in the repository. I have followed the prescribed guidelines and ensured that all necessary details are accurate and align with the required data structure. Below is an overview of the tokens and the associated changes.
- [x] I have checked that the format of my PR follows the contribution guidelines

### Token Overview &#128221;
- Token Names: Cult DAO, ChainGPT, Stargate Finance
- Token Tickers: CULT, CGPT, STG
- Blockchain: Ethereum (for all tokens)
- Token Type: ERC20 Tokens (for all tokens)
- Primary Use Cases: 
  - Cult DAO (CULT): Utility token for Cult DAO, where a small percentage of every CULT transaction funds the DAO treasury, which is used to invest in decentralized technologies.
  - ChainGPT (CGPT): Utility token for ChainGPT, an open AI-driven platform providing LLMs, APIs, and SDKs for Web3 users and companies to integrate AI solutions into their products.
  - Stargate Finance (STG): Utility token for Stargate Finance, an omnichain-native bridge that facilitates cross-chain DeFi transactions, allowing users to transfer assets seamlessly across multiple blockchains and decentralized applications (dApps).

### Organization Details &#127970;
- Organization Names: Cult DAO, ChainGPT, Stargate Finance
- Websites: 
  - Cult DAO: https://cultdao.io/
  - ChainGPT: https://www.chaingpt.org/
  - Stargate Finance: https://stargate.finance/
- Mission & Vision:
  - Cult DAO: To support decentralized technologies through a community-driven DAO, funded by a percentage of all CULT transactions.
  - ChainGPT: To provide open and accessible AI solutions to Web3 users and companies, enabling them to leverage the power of AI in their decentralized applications.
  - Stargate Finance: To solve the blockchain trilemma by providing an omnichain-native bridge that facilitates fast, secure, and decentralized cross-chain DeFi transactions.

### Changes Proposed &#128260;
#### For Additions:
- Community Demand: 
  - CULT: Increasing demand for decentralized platforms that fund Web3 development through community-driven DAOs.
  - CGPT: Growing interest in AI solutions for blockchain applications, with ChainGPT offering open tools for developers and enterprises.
  - STG: High demand for seamless cross-chain transactions as DeFi expands across multiple blockchains and layer-2 networks.
- Unique Value Proposition:
  - CULT: A percentage of every transaction funds the Cult DAO, supporting investments in decentralized technologies.
  - CGPT: Open AI-driven platform providing tools, APIs, and SDKs for Web3 users to integrate AI into their products.
  - STG: Provides an omnichain-native bridge that allows for fast, decentralized cross-chain asset transfers.
- Technical Robustness: 
  - All tokens are built on Ethereum's secure blockchain, ensuring scalability and decentralized governance.
  - STG facilitates cross-chain transactions with omnichain-native support, simplifying DeFi interactions across multiple blockchains.
- Compliance and Security: 
  - All tokens comply with Ethereum's security standards, with regular audits and updates to ensure the reliability and security of their respective platforms.

### Rationale for Inclusion/Modification &#128200;
- Benefits to the Repository: 
  - Adds diverse Ethereum tokens representing decentralized technologies funding (CULT), AI integration for blockchain (CGPT), and cross-chain DeFi solutions (STG).
  - Expands the range of use cases and technical capabilities within the MELD ecosystem.
- Impact on Community:
  - Provides exposure to decentralized community funding, AI-driven blockchain tools, and seamless cross-chain DeFi transactions.
  - Attracts users interested in decentralized governance, AI solutions for Web3, and cross-chain interoperability.

2024-10-03 13:24 UTC, infrmtcs commented on networks/ethereum/tokens/0x9840652DC04fb9db2C43853633f0F62BE6f00f98.json
> +  "tokenAddress": "0x9840652DC04fb9db2C43853633f0F62BE6f00f98",
This address is for BNB smart chain, not Ethereum mainnet.

2024-10-03 13:25 UTC, infrmtcs requested changes
Please address the comments above, thanks.

2024-10-03 13:32 UTC, rebelC0der reviewed
Sorry, still perfecting my automated script.

2024-10-04 07:37 UTC, thuyvu17 approved these changes

2024-10-04 09:32 UTC, infrmtcs approved these changes

2024-10-04 09:32 UTC, merged